### ISSUE TITLE
BadParcelableException when reading a Parcelable from a Request inside an Operation

### ISSUE THREAD

**Issue by Maragues** [foxykeep/DataDroid#14]
**Issue:** Attempting to read a Parcelable attached to a Request inside an Operation throws a BadParcelableException because it can't find the class

```
E/Parcel(13418): Class not found when unmarshalling: com.maragues.parcelabletestdatadroid.data.model.City, e: java.lang.ClassNotFoundException: com.maragues.parcelabletestdatadroid.data.model.City
```

I've created a project demonstrating the issue: https://github.com/Maragues/ParcelableTestDataDroid

**Reason:** My guess is that because the Operation runs in a different thread, the Bundle containing the Parcelable doesn't have access to a ClassLoader that can load the parcelable.

**Fix:** The simplest way to fix this is setting the current Thread class loader at com.foxykeep.datadroid.requestmanager.Request.java

``` java
public Parcelable getParcelable(String name) {
            mBundle.setClassLoader(Thread.currentThread().getContextClassLoader());
            return mBundle.getParcelable(name);
    }
```

Another option is to add a Context parameter and get the classLoader from it, but that would break the library usage

As I'm not sure if there are better solutions, I haven't done a pull request. 

(maybe I should do the pull request any way, just say. This is my first issue report...)

**Comment by foxykeep** [comment]
I should have and can add the classloader for you inside the RequestService. So that the API doesn't change and you have nothing else to do.
I'm going to make a patch today to fix that and update the library.

Sorry for that. I've tried the Parcelable in the Request but with the Bitmap which is part of the SDK and therefore doesn't need the special classLoader.

Thanks for your feedback !

**Comment by Maragues** [comment]
That sounds like a better idea.

thanks for the library and for your dedication
