### ISSUE TITLE
Trying to use datadroid and sliding menu

### ISSUE THREAD

**Issue by ccfiel** [foxykeep/DataDroid#17]
I am new in android so please bare with me if I ask stupid question :) I am trying to used datadroid and sliding menu. Sliding is using fragment. Is it possible that datadroid will be a fragment to a main activity? :) I have successfully made a datadroid app in just one activity like this.

public final class tonesListActivity extends DataDroidActivity implements RequestListener,
        OnClickListener, ConnectionErrorDialogListener, LoaderCallbacks<Cursor> {
.....

but how about if datadroid is a fragment of an main activity? any idea?

chris

**Comment by foxykeep** [comment]
I didn't try to use it with a Fragment recently but I don't see any reason why it shouldn't work

I'm going to try to find some time to test and add a sample which uses fragment to show how to use it

**Comment by Maragues** [comment]
Hi, I'm using SlidingMenu + DataDroid but through the object instead of extending their class. Here's some basic code

``` java
public abstract class DataDroidActivity extends SherlockFragmentActivity {
    //DataDroid stuff

    protected SlidingMenu mSlidingMenu;
```

Then, various configuration and usage functions

``` java
private void configureSideMenu() {
        mSlidingMenu = new SlidingMenu(this);
        mSlidingMenu.setTouchModeAbove(SlidingMenu.TOUCHMODE_FULLSCREEN);
        mSlidingMenu.setFadeDegree(0.35f);
        mSlidingMenu.attachToActivity(this, SlidingMenu.SLIDING_CONTENT);
        mSlidingMenu.setBehindOffsetRes(R.dimen.slidingmenu_offset);
        mSlidingMenu.setMenu(R.layout.menu_frame);
        getSupportFragmentManager()
        .beginTransaction()
        .replace(R.id.menu_frame, new MySideMenuFragment())
        .commit();
    }

@Override
    public void onBackPressed() {
        if (mSlidingMenu.isMenuShowing()) {
            mSlidingMenu.showContent();
        } else {
            super.onBackPressed();
        }
    }

@Override
    public boolean onOptionsItemSelected(MenuItem item) {       
        switch (item.getItemId()) {
           case android.R.id.home:
            mSlidingMenu.toggle();
            return true;
          //more stuff
```

Hope you find this usefull

**Comment by ccfiel** [comment]
thanks! a I will try you idea :)
