### ISSUE TITLE
Count number of Records in a model

### ISSUE THREAD

**Issue by ccfiel** [foxykeep/DataDroid#19]
Hello guys,

How to count number of records of a data model? Any ideas? :)

Best Regards

Chris

**Comment by foxykeep** [comment]
What do you mean by number of records ? And when you say data model, you mean contentprovider ?

**Comment by ccfiel** [comment]
foxykeep,

Yes I mean the contentprovider. sorry for the confusion :) any idea?

Best Regards,

Chris

**Comment by foxykeep** [comment]
Easiest way is to do a query with the right table without any where clause. and then call getCount on the returned Cursor.

As you don't have any where clause, you get all the elements in the cursor and getCount() will give you the number
