### ISSUE TITLE
Httpurlconnection request with PUT method with cookies gives session invalid error.

### ISSUE THREAD

**Issue by nilkashid** [foxykeep/DataDroid#23]
Hi I am using datadroid library. When i tried to call PUT API call with my session data it gives me session does not exits error from my server side. But when i tried with GET API call its working fine.
I tried it in this way http://stackoverflow.com/questions/15515346/maintaining-session-with-cookies-android.
Can you plz help me to figure out what I am doing wrong here. Need help thank you.

**Comment by nilkashid** [comment]
Whether it handling cookies or not. Need help. thank you..

**Comment by foxykeep** [comment]
Are you sure your server is handling the sessions parameter in the PUT case ?
Did you add logs on your server to make sure the session object are not there ? 

Another thing, I've just submitted a change which modify the way PUT requests are executed to be more like the way POST requests are executed. can you try again and tell me if it fixes your issue ?

**Comment by nilkashid** [comment]
Hye I solve this problem. Actually What happened I wanted to send some data with put request and when i passed it it append it to my url. My server was not able to handle that request. I made some changes into library. I m using 
connection.setDoOutput(true); for my put method. passing my data into output stream. This works fine for my older version of device. But when I tried it with ICS it gives me error for  connection.setDoOutput(true); 

It gives following error:
E/RequestService(28321): ConnectionException
E/RequestService(28321): com.foxykeep.datadroid.exception.ConnectionException: HTTP Method not allowed

When I remove 
connection.setDoOutput(true); its working on ICS as well but then my put method is not working.

How to solve this. Need Help. 
Thank you for such a great work and great support.

**Comment by foxykeep** [comment]
As I said, update your datadroid code to the latest and it will be fixed for you normally :)

PUT requests are now executed the same way as POST requests with the parameter in the body instead of the URL

**Comment by nilkashid** [comment]
Thank you sir. I will try it. thank you for your good support. So simillar way i have to pass my parameter like 
 networkConnection.setParameters(user_params) for put method as well and it will take it as body not in url. Right?

**Comment by foxykeep** [comment]
Exactly. You don't have to change anything on your side and it will be added as part of the body.

Closing the issue for now. Reopen it if it doesn't work.

**Comment by nilkashid** [comment]
yeah sure. Thank you.

**Comment by nilkashid** [comment]
But is there any specific reason why it is giving error for ics with setdataoutput ?

**Comment by nilkashid** [comment]
We are setting output text for post method. For put method also we have to set that one? or that is not required?

**Comment by foxykeep** [comment]
It is set for you by the code in NetworkConnectionImpl.

And I dont know why it crashed on ICS. normally it shouldn't .... I just
tried on GB and it works without issue

Nicolas KLEIN aka Foxykeep

**Comment by nilkashid** [comment]
yeah sir actually that's work fine for GB But for ICS it gives error for my code. I will try your solution. And let you whether its working or not. 

Thank you.

**Comment by foxykeep** [comment]
Ok ! Keep me posted

Nicolas KLEIN aka Foxykeep
