### ISSUE TITLE
how to apply migration to existing application

### ISSUE THREAD

**Issue by ccfiel** [foxykeep/DataDroid#29]
I have made application using datadroid my problem is I have added a price field in my table. how to I migrated the new field? The application is now existing in google play. And I want to add price field. Is it possible?

**Comment by foxykeep** [comment]
Check [ContentProviderCodeGenerator](https://github.com/foxykeep/ContentProviderCodeGenerator).

You have way to generate content providers with it with the new fields (in your case your price field) for your new versions without losing the existing data in your database :)
