### ISSUE TITLE
Feature Request: no verify ssl option

### ISSUE THREAD

**Issue by saik0** [foxykeep/DataDroid#3]
I'll be working on this soon, wondering whether this is something you want in the project or if I should just subclass.

**Comment by saik0** [comment]
This is looking like it's going to be non-trivial. We'll probably have to extend AndroidHttpClient and override newInstance()

**Comment by saik0** [comment]
And of course AndroidHttpClient is final, grrrr. Are we against implementing HttpClient ourselves using AndroidHttpClient as a base?

**Comment by foxykeep** [comment]
I'm currently completely rewriting my NetworkConnection class to switch automatically between AndroidHttpClient and HttpURLConnection based on the Android version (cf http://android-developers.blogspot.fr/2011/09/androids-http-clients.html), as well as implementing another version for 1.6 as AndroidHttpClient is not available for these versions.

So I'll see if I can add the verify ssl option at the same time

**Comment by saik0** [comment]
great! I didn't want to make any huge changes like that as a contributor but that's perfect. I was also going to suggest using a Builder sort of class but looks like you're one step ahead of me again ;)

**Comment by saik0** [comment]
You might reduce the complexity by using your own HttpClient impl on all < api 10, AndroidHttpClient is just for convenience, if we're doing the hard work ourselves there's no need for it. No?

**Comment by foxykeep** [comment]
That was pretty much what I was thinking for API < 10 :)

**Comment by saik0** [comment]
Not sure what the release schedule looks like for NetworkConnection v2 but [pull request 9](https://github.com/foxykeep/DataDroid/issues/9) should work for now.

**Comment by foxykeep** [comment]
The version 2 of datadroid now allows to disable SSL validation.
