### ISSUE TITLE
Sending Json Object as parameter in post method

### ISSUE THREAD

**Issue by nilkashid** [foxykeep/DataDroid#34]
hi I am using this library for network operation and its working fine. First of all this is not a issue. In one my network call I want to send json object in my post request. So i need your help to send json object in set params method. i tried it in regular way but its not working for me.

My json object is looks like this {param1:"value1"; param2["value21","value22"]};
how to send it with post request need help thank you.

**Comment by foxykeep** [comment]
You can use NetworkConnection.setPostText() to send your JSON object. You just need to serialize it into a string.
