### ISSUE TITLE
Why have you decided to skip the approach of ContentProvider ?

### ISSUE THREAD

**Issue by asaf** [foxykeep/DataDroid#36]
Hey,

In the workflow presented back in 2010 there is a heavy usage of ContentProvider,

I'm curious, why have you decided not to implement the solution based on ContentProviders at all?

Thanks.

**Comment by foxykeep** [comment]
I choose to implement solution A from the workflow presented during the IO session on REST which doesn't use directly a content provider for it. The main reason was that I had some use cases where I didn't need to save the data in a ContentProvider (so there would have been overhead for nothing). 

Also at this time I didn't know how to implement solution B or C which were using a ContentProvider as the front interface :)
