### ISSUE TITLE
Feature Request: http auth

### ISSUE THREAD

**Issue by saik0** [foxykeep/DataDroid#4]
I might work on this after ssl_no_verify. I might also be lazy and just manually add Authorization headers to my requests :)

Thoughts?

**Comment by foxykeep** [comment]
Never had to work with http auth, so I didn't add it yet. But it could be a good addition. 

The rewrite of NetworkConnection will provide a Builder (Like the AlertDialog.Builder class) so we could totally provide an helper method to create the header. 
I'll add it in the new version of NetworkConnection :)

**Comment by saik0** [comment]
Not sure what the release schedule looks like for NetworkConnection v2 but [pull request 9](https://github.com/foxykeep/DataDroid/issues/9) should work for now.

**Comment by foxykeep** [comment]
This feature has been added in datadroid v2
